<?php ?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Information — VOTIVA</title><link rel="stylesheet" href="assets/style.css"><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@500;600;700&display=swap" rel="stylesheet"></head><body><header class="site-header"><div class="nav wrap"><a class="brand" href="index.php">VOTI<span>V</span>A</a><a class="back" href="index.php">← Home</a></div></header><main class="legal wrap"><span class="kicker">VOTIVA JOURNAL</span><h1>Information &amp; Stories</h1><p class="lead">A simple place to understand the people and debates featured in our polls.</p>
<section class="blog-grid">
<article><span>CRICKET</span><h2>MS Dhoni</h2><p>MS Dhoni is celebrated for calm leadership, wicketkeeping and finishing ability. His career has made him one of India's most recognisable cricket figures.</p></article>
<article><span>CRICKET</span><h2>Virat Kohli</h2><p>Virat Kohli is known for elite batting, intensity and consistency across formats. His competitive approach has created a huge global following.</p></article>
<article><span>FOOTBALL</span><h2>Cristiano Ronaldo</h2><p>Cristiano Ronaldo is one of football's most decorated and recognisable forwards, renowned for goal scoring, athleticism and longevity.</p></article>
<article><span>FOOTBALL</span><h2>Lionel Messi</h2><p>Lionel Messi is renowned for close control, creativity, playmaking and scoring. His career has established him as one of football's defining stars.</p></article>
<article><span>MOVIE</span><h2>Dhurandhar</h2><p>Dhurandhar is a high-profile Hindi action project that has generated strong audience discussion and anticipation.</p></article>
<article><span>MOVIE</span><h2>Pathaan</h2><p>Pathaan is a major Hindi action entertainer from YRF's spy universe, known for its large-scale spectacle and star power.</p></article>
<article><span>CELEBRITY</span><h2>Shah Rukh Khan</h2><p>Shah Rukh Khan is one of India's most prominent film stars, with a career spanning decades and a worldwide fan base.</p></article>
<article><span>CELEBRITY</span><h2>Ranveer Singh</h2><p>Ranveer Singh is known for energetic performances, distinctive style and a wide range of roles in contemporary Hindi cinema.</p></article>
<article><span>OTHER</span><h2>Khan Sir</h2><p>Khan Sir is widely known for educational content and accessible teaching aimed at competitive-exam learners.</p></article>
<article><span>OTHER</span><h2>Avadh Ojha</h2><p>Avadh Ojha is an educator and public speaker associated with civil-services preparation and motivational educational content.</p></article>
</section>
<section class="about-box"><span class="kicker">ABOUT VOTIVA</span><h2>What is VOTIVA?</h2><p>VOTIVA is designed for transparent public opinion. A vote is accepted by the server, stored in the database and included in the result calculation. The interface does not manufacture or randomly change percentages.</p></section>
</main><footer><div class="wrap footer-grid"><div><a class="brand" href="index.php">VOTI<span>V</span>A</a></div><div class="footer-links"><a href="privacy.php">Privacy</a><a href="terms.php">Terms</a></div></div></footer></body></html>